name:                object-store
version:             0.1.0.0
github:              "VannTen/object-store"
license:             BSD3
author:              "Max Gautier"
maintainer:          "mg@max.gautier.name"
copyright:           "2022 Max Gautier"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/VannTen/object-store#readme>

dependencies:
- base >= 4.7 && < 5
- servant < 0.20
- warp
- bytestring
- utility-ht

library:
  source-dirs: src

executables:
  object-store-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - object-store
    - servant-server
    - warp
